apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-oci-deployment-jco
  namespace: ns-jco
spec:
  selector:
    matchLabels:
      app: hola-oci
  replicas: 1
  template:
    metadata:
      labels:
        app: hola-oci
    spec:
      containers:
      - name: hola-oci
        image: iad.ocir.io/ocuocictrng30/hola_oci:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocir-secret-jco
---
apiVersion: v1
kind: Service
metadata:
  name: hola-oci-service-jco
  namespace: ns-jco
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hola-oci
